In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [7]:
data = pd.read_csv('bank.csv', header=0)
data = data.dropna()
print(data.shape)
print(list(data.columns))

(11162, 17)
['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'deposit']

In [8]:
data.head()

   age         job  marital  education  ... pdays  previous poutcome deposit
0   59      admin.  married  secondary  ...    -1         0  unknown     yes
1   56      admin.  married  secondary  ...    -1         0  unknown     yes
2   41  technician  married  secondary  ...    -1         0  unknown     yes
3   55    services  married  secondary  ...    -1         0  unknown     yes
4   54      admin.  married   tertiary  ...    -1         0  unknown     yes

[5 rows x 17 columns]

In [9]:
data['education']=np.where(data['education'] =='basic.9y', 'Basic', data['education'])
data['education']=np.where(data['education'] =='basic.6y', 'Basic', data['education'])
data['education']=np.where(data['education'] =='basic.4y', 'Basic', data['education'])